centos7-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /opt/rh/devtoolset-8/enable
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-x86_64.tar.gz
  - tar xf cmake-3.23.0-linux-x86_64.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-x86_64/bin/cmake
  - make self GRDIR=/usr/local/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gks/qt/gksqt artifacts/gksqt
  - cp lib/grm/grplot/grplot artifacts/grplot
  - cp lib/grm/grplot/README.md artifacts/grplot.man.md
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so
       lib/gr3/libGR3platform.so lib/grm/libGRM.a lib/grm/libGRM.so lib/gr/qtgr/*.so artifacts/
  - cp -r lib/gks/fonts artifacts/
  - mkdir artifacts/include/
  - cp lib/gks/gks.h lib/gr/gr.h lib/gr3/gr3.h lib/grm/include/grm.h lib/gr/qtgr/grwidget.h artifacts/include/
  - cp -r lib/grm/include/grm artifacts/include/
  - mv artifacts artifacts-centos7
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7/

centos7-cmake-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-self-contained
  script:
  - source /opt/rh/devtoolset-8/enable
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-x86_64.tar.gz
  - tar xf cmake-3.23.0-linux-x86_64.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-x86_64/bin/cmake
  - make -C 3rdparty default extras
  - mkdir build
  - cd build
  - $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=ON
  - make
  - make install
  - mv ../install/lib64/ ../install/lib/
  - cd ..
  - mv install artifacts-centos7-cmake
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7-cmake/

centos7-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /opt/rh/devtoolset-8/enable
  - make install GRDIR=/usr/local/gr

centos7-cmake-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-system-dependencies
  script:
  - source /opt/rh/devtoolset-8/enable
  - yum install -y libjpeg-turbo-devel libtiff-devel bzip2-devel
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-x86_64.tar.gz
  - tar xf cmake-3.23.0-linux-x86_64.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-x86_64/bin/cmake
  - make -C 3rdparty default TARGETS="qhull"
  - mkdir build
  - cd build
  - $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DCMAKE_FIND_ROOT_PATH=$(cd ../3rdparty/build && pwd)
  - make

centos7-32bit-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /opt/gcc-8.5.0/enable
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-i386.tar.gz
  - tar xf cmake-3.23.0-linux-i386.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-i386/bin/cmake
  - THEORA_EXTRA_CONFIGURE_FLAGS=--disable-asm
    OPENH264_EXTRA_MAKE_FLAGS=ARCH=i386
    EXTRA_LDFLAGS="-static-libstdc++ -static-libgcc"
    make self GRDIR=/usr/local/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gks/qt/gksqt artifacts/gksqt
  - cp lib/grm/grplot/grplot artifacts/grplot
  - cp lib/grm/grplot/README.md artifacts/grplot.man.md
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so
       lib/gr3/libGR3platform.so lib/grm/libGRM.a lib/grm/libGRM.so lib/gr/qtgr/*.so artifacts/
  - cp -r lib/gks/fonts artifacts/
  - mkdir artifacts/include/
  - cp lib/gks/gks.h lib/gr/gr.h lib/gr3/gr3.h lib/grm/include/grm.h lib/gr/qtgr/grwidget.h artifacts/include/
  - cp -r lib/grm/include/grm artifacts/include/
  - mv artifacts artifacts-centos7-32bit
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7-32bit/

centos7-32bit-cmake-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-32bit-self-contained
  script:
  - source /opt/gcc-8.5.0/enable
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-i386.tar.gz
  - tar xf cmake-3.23.0-linux-i386.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-i386/bin/cmake
  - THEORA_EXTRA_CONFIGURE_FLAGS=--disable-asm
    OPENH264_EXTRA_MAKE_FLAGS=ARCH=i386
    make -C 3rdparty default extras
  - mkdir build
  - cd build
  - LDFLAGS="-static-libstdc++ -static-libgcc"
    $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=ON
  - make
  - make install
  - cd ..
  - mv install artifacts-centos7-32bit-cmake
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7-32bit-cmake/

centos7-32bit-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /opt/gcc-8.5.0/enable
  - EXTRA_LDFLAGS="-static-libstdc++ -static-libgcc"
    make install GRDIR=/usr/local/gr

centos7-32bit-cmake-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/centos7-32bit-system-dependencies
  script:
  - source /opt/gcc-8.5.0/enable
  - yum install -y libtiff-devel bzip2-devel
  - curl -LO https://gr-framework.org/downloads/3rdparty/cmake-3.23.0-linux-i386.tar.gz
  - tar xf cmake-3.23.0-linux-i386.tar.gz
  - export CMAKE_CMD=`pwd`/cmake-3.23.0-linux-i386/bin/cmake
  - make -C 3rdparty default TARGETS="qhull"
  - mkdir build
  - cd build
  - LDFLAGS="-static-libstdc++ -static-libgcc"
    $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DCMAKE_FIND_ROOT_PATH=$(cd ../3rdparty/build && pwd)
  - make
