arch-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
    - make self GRDIR=/usr/local/gr
    - mkdir artifacts
    - cp lib/gks/demo artifacts/gksdemo
    - cp lib/gks/qt/gksqt artifacts/gksqt
    - cp lib/grm/grplot/grplot artifacts/grplot
    - cp lib/grm/grplot/README.md artifacts/grplot.man.md
    - cp lib/gr/demo artifacts/grdemo
    - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so
         lib/gr3/libGR3platform.so lib/grm/libGRM.a lib/grm/libGRM.so lib/gr/qtgr/*.so artifacts/
    - cp -r lib/gks/fonts artifacts/
    - mkdir artifacts/include/
    - cp lib/gks/gks.h lib/gr/gr.h lib/gr3/gr3.h lib/grm/include/grm.h lib/gr/qtgr/grwidget.h artifacts/include/
    - cp -r lib/grm/include/grm artifacts/include/
    - mv artifacts artifacts-arch
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts-arch/

arch-cmake-self-contained:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-self-contained
  script:
    - make -C 3rdparty default extras
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=ON -DCMAKE_INSTALL_LIBDIR=${CI_PROJECT_DIR}/install/lib
    - make
    - make install
    - cd ..
    - mv install artifacts-arch-cmake
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts-arch-cmake/

arch-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
    - make install GRDIR=/usr/local/gr

arch-cmake-system-dependencies:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/arch-system-dependencies
  script:
    - pacman -Sy
    - pacman -S --noconfirm --needed qhull
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install -DGR_USE_BUNDLED_LIBRARIES=OFF
    - make
