emscripten:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /emsdk/emsdk_env.sh
  - emmake make -C js
  - mkdir artifacts
  - cp js/gr.js artifacts/
  - mv artifacts artifacts-js
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-js/
  # Is needed to circumvent a bug in GitLab CI (if needed jobs do not contain a rule section, but the dependent job
  # does, GitLab CI produces YAML errors)
  rules:
  - when: on_success
