emscripten:
  stage: build
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  script:
  - source /emsdk/emsdk_env.sh
  - emmake make -C js
  - mkdir artifacts
  - cp js/gr.js artifacts/
  - mv artifacts artifacts-js
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-js/
