emscripten-test:
  stage: test
  image: iffregistry.fz-juelich.de/scientific-it-systems/gr-test/js-testing
  rules:
  - if: '$CI_MERGE_REQUEST_ID'
    when: never
  - when: on_success
  needs:
  - emscripten
  script:
  - export GR_JS=`pwd`/artifacts-js/gr.js
  - gr_test js `pwd`/test_result/
  artifacts:
    paths:
    - test_result/
    when: on_failure
